#!/bin/bash
options=(
    style=round
    width=10.0
    hidpi=off
    # active_color=0xff8f9fa
    # active_color=0xff93b259 # green
    active_color=0xffbf68d9 # magenta
    # active_color=0xff8aadf4 # blue
    inactive_color=0xff333333
)
borders "${options[@]}"
